// The shared artifact: an untyped runtime mirror of Agda's Rx.Exp.
// Trees are DATA — generated by the prop-test generator, serialized to
// JSON for the Agda decoder, and compiled onto the real-rxjs
// primitives on this side.
//
// Well-typedness and μ-guardedness are NOT tracked by these types; the
// generator maintains them and the Agda decoder re-checks them. Every
// node carries its result Ty so that re-check is a local structural
// comparison, never inference.

// Agda: Rx.Exp.Ty
export type Ty =
  | { type: "unit" }
  | { type: "bool" }
  | { type: "nat" }
  // an identity TOKEN: a host `symbol`, with only equality on it, so no
  // program can do arithmetic on one or invent one that was never
  // minted. That is the whole of the difference from nat, and it is
  // what lets a simul operator key a value by where it came from.
  //
  // A SYMBOL RATHER THAN A NUMBER, AND IT IS THE NUMERAL'S REMOVAL THAT
  // FREED THE REPRESENTATION.  `uniqT` used to CARRY a number, so a
  // program could name an arbitrary token, and the number TS handed out
  // had to be the number Agda's counter would hand out at the same point
  // -- two independent evaluators kept in lockstep by nothing the
  // typechecker could see.  Nullary, the literal names ONE reserved
  // token and every other token comes from a `mint` binder, so all that
  // is left at this type is identity, and the representation is free --
  // and `symbol` is the one host type whose values cannot be forged,
  // counted or ordered, which is exactly what the type says.
  | { type: "uniq" }
  | { type: "prod"; fst: Ty; snd: Ty }
  | { type: "sum"; left: Ty; right: Ty }
  | { type: "obs"; elem: Ty }
  // lists are the pure-function former's own currency: a step reads the
  // emit's values as one and returns the values to emit in their place,
  // so the value language needs them even though no emit ever carries
  // one. Nothing constructs a list-typed observable.
  | { type: "list"; elem: Ty };

// Concrete stand-in for Agda's `PrimOp` postulate — the Agda side must
// become this exact datatype before the JSON bridge lands. Binary ops
// take a pair argument; sub is ℕ monus (truncated at 0).
// `eqU` is the only operation on a uniq, and it is a separate op rather
// than `eq` widened because that is what keeps the token opaque: sharing
// one op would type it at nat and hand every nat operation to it.
export type PrimOp = "add" | "sub" | "mul" | "eq" | "lt" | "not" | "eqU";

// Agda: Rx.Exp.Val. unit = null. An obs-typed value is a CLOSURE — the
// body it was written as, paired with the environment it was written
// under — never a closed Exp and never a host closure.
// A pair and a list are both arrays at runtime and are told apart by
// the TYPE at every site that needs to; nothing else inspects a value's
// shape, and no emit value is ever list-typed.
//
// THE ENVIRONMENT IS WHAT REPLACED SUBSTITUTION, AND IT IS WHY THE TOKEN
// LITERAL NEEDS NO PAYLOAD.  Closing a body by substituting its
// environment in demanded a closed Tm denoting every value a binder
// could carry, a MINTED token included, and the only such term is one
// carrying a numeral.  Carrying the environment instead asks for no such
// term: a minted token sits in the environment as a runtime value, and
// the one token the language can still write is the reserved literal,
// which needs nothing written down to name it.
export type ObsVal = { exp: Exp; env: Val[] };

// the value `uniqT` denotes: one reserved token, distinct from every
// minted one because `mintToken` returns a FRESH symbol and no symbol is
// ever equal to another. Agda reserves the same token arithmetically --
// the identifier just above the slot range, which its source counter is
// seeded past -- because its tokens are numbers and it has no such
// freshness for free.
export const UNIQ_LITERAL: unique symbol = Symbol("uniq-literal");

export type Val =
  | null
  | boolean
  | number
  | symbol // a uniq token: minted, or the reserved literal
  | [Val, Val]
  | Val[]
  | { type: "inl" | "inr"; val: Val }
  | ObsVal;

// Agda: Rx.Exp.Tm — first-order terms, the only function language.
// All variables are de Bruijn indices. Θ-binders (map/scan fns, case
// branches) bind their argument as varT index 0.
export type Tm =
  | { type: "varT"; ty: Ty; index: number } // into Θ
  | { type: "unitT"; ty: Ty }
  | { type: "boolT"; ty: Ty; val: boolean }
  | { type: "natT"; ty: Ty; val: number }
  // the ONE token a program may write, and it carries no payload. A
  // parameter here would let a program name an arbitrary token — the
  // forgery `mint` exists to rule out — and would oblige this evaluator
  // and Agda's to hand out the same numeral at the same point. Nullary,
  // it names one RESERVED token: here a dedicated symbol no `mintToken`
  // can return, in Agda the identifier just above the slot range, which
  // its source counter is seeded past. So every equality a program can
  // ask about it has the same answer in both trees.
  | { type: "uniqT"; ty: Ty }
  | { type: "pairT"; ty: Ty; fst: Tm; snd: Tm }
  | { type: "fstT"; ty: Ty; pair: Tm }
  | { type: "sndT"; ty: Ty; pair: Tm }
  | { type: "inlT"; ty: Ty; val: Tm }
  | { type: "inrT"; ty: Ty; val: Tm }
  | { type: "caseT"; ty: Ty; scrut: Tm; onInl: Tm; onInr: Tm } // branches bind Θ-var 0
  | { type: "ifT"; ty: Ty; cond: Tm; then: Tm; else: Tm }
  | { type: "primT"; ty: Ty; op: PrimOp; arg: Tm }
  | { type: "strmT"; ty: Ty; exp: Exp } // streams as values — how higher-order operators work
  | { type: "nilT"; ty: Ty }
  | { type: "consT"; ty: Ty; head: Tm; tail: Tm }
  // a LEFT fold: step binds the element as Θ-var 0 and the accumulator
  // as Θ-var 1. It is the term language's only eliminator that binds
  // more than one thing, and the only way to hand a step an argument —
  // there is no application here.
  | { type: "foldT"; ty: Ty; list: Tm; init: Tm; step: Tm };

// Agda: Fn Γ Δᵍ Δ Θ s t = Tm with the argument bound as Θ-var 0.
export type Fn = Tm;

export type Exp =
  | { type: "input"; ty: Ty; index: number } // into Γ
  | { type: "of"; ty: Ty; items: Tm[] }
  | { type: "empty"; ty: Ty }
  // THE pure-function formers, and there are two because rxjs has two.
  // Each step is POINTWISE: map's Θ-var 0 is one source value, scan's is
  // the pair (carried state, one source value), and each returns one
  // value. An emit carries a LIST of them, so the step runs once per
  // element and the frame is never something it can see — which is what
  // stops a program writing one.
  //
  // A scan's carried value IS its output, so the node's own `ty` pins
  // both and `init` needs no type of its own; neither former derives
  // from the other, which is why rxjs ships both.
  | { type: "map"; ty: Ty; fn: Fn; src: Exp }
  | { type: "scan"; ty: Ty; fn: Fn; init: Tm; src: Exp }
  | { type: "take"; ty: Ty; count: Tm; src: Exp } // count evaluated once, at subscription time
  // NOTE: share is NOT an Exp node — share identity is a binding, not
  // an expression. Shared observables live in the slot telescope
  // (prop-test's Slot) and are referenced with `input`, exactly like
  // scripted inputs.
  // ONE higher-order primitive carrying rxjs's `concurrent` argument:
  // ABSENT is Infinity (mergeAll), 1 is concatAll, k >= 2 is the bounded
  // mergeMap(f, k) that has no name of its own in rxjs. The limit is a
  // literal and NOT a Tm, unlike take's count: rxjs fixes `concurrent`
  // when the pipeline is BUILT, not when it is subscribed. Unbounded is
  // an ABSENT field rather than null so that JSON.stringify drops it and
  // the Agda decoder reads the limit as `getField "limit" >>=? asNum` —
  // a Maybe with no null constructor needed in the JSON grammar.
  | { type: "mergeAll"; ty: Ty; limit?: number; src: Exp }
  | { type: "switchAll"; ty: Ty; src: Exp }
  | { type: "exhaustAll"; ty: Ty; src: Exp }
  | { type: "mu"; ty: Ty; body: Exp } // binds a μ-var, GUARDED (Agda's Δᵍ)
  | { type: "varE"; ty: Ty; index: number } // into the μ-binder stack, usable vars only (Agda's Δ)
  | { type: "defer"; ty: Ty; body: Exp }
  // binds one fresh uniq token per subscription, extending Θ by uniqᵗ.
  // The body sees the token as Θ-var 0; unlike defer it does NOT touch
  // Δᵍ/Δ (μ-vars), only Θ.
  | { type: "mint"; ty: Ty; body: Exp }
  // the one plain former that can see synchrony, and it sees exactly one
  // bit of it: the subscribe frame's values leave as ONE group, every
  // later value as its own singleton. `ty` is the node's own type, so a
  // batchSync over `s` carries `s ×ᵗ listᵗ s` — head and tail, since the
  // group is never empty. NOTHING COMPILES IT YET: the plain-rxjs
  // refactor of the primitives is what has to write the operator, and
  // until then the generator has no lane for it (scripts/formers.tsv).
  | { type: "batchSync"; ty: Ty; src: Exp };
// ⚠ defer here is Agda's deferᵉ, NOT rxjs defer: lazy PLUS a one-tick
// hop, and the body's emissions mint fresh ids (an async boundary).
//
// μ-guardedness (Agda's Δᵍ/Δ split, enforced there by typing): a varE
// may only reference a mu binder if the path between them crosses at
// least one defer. Synchronous self-reference is invalid — generator
// invariant, re-checked by the Agda decoder.

// Agda: Closed Γ t — no free Θ-vars or μ-vars; input nodes are allowed.
export type Closed = Exp;

// Substitution plumbing — twins of Agda's evalTm/applyFn/unfoldμ,
// used by the rx compiler: evalTm/applyFn turn Tm functions into host
// functions for map/scan/take, unfoldMu ties the μ knot. (Agda's wkᵍ
// has no twin: with de Bruijn indices, weakening is the index shift
// performed inside unfoldMu — and the substituted term is CLOSED, so
// no shift is actually needed.)

// ---- evalTm / applyFn: evaluate a Tm in a Θ value-environment ----
// env is the Θ context, index 0 = innermost binder. A closed Tm is
// evaluated in the empty environment; a Fn is evaluated with its one
// argument bound at index 0. The only value language is first-order.

// a nat prim op on two nats; sub is ℕ monus (truncated at 0)
const applyPrim = (op: PrimOp, arg: Val): Val => {
  if (op === "not") return !(arg as boolean);
  const [a, b] = arg as [Val, Val]; // add/sub/mul/eq/lt take a pair
  switch (op) {
    case "add":
      return (a as number) + (b as number);
    case "sub":
      return Math.max(0, (a as number) - (b as number));
    case "mul":
      return (a as number) * (b as number);
    case "eq":
      return valEq(a, b);
    case "lt":
      return (a as number) < (b as number);
    case "eqU":
      return a === b; // tokens are compared by identity and nothing else
  }
};

// structural equality over the value domain (nats/bools/unit by ===,
// pairs and sums recursively; observables never reach eq)
const valEq = (a: Val, b: Val): boolean => {
  if (Array.isArray(a) && Array.isArray(b))
    return valEq(a[0], b[0]) && valEq(a[1], b[1]);
  if (
    a !== null &&
    b !== null &&
    typeof a === "object" &&
    typeof b === "object" &&
    "type" in a &&
    "type" in b &&
    (a.type === "inl" || a.type === "inr") &&
    (b.type === "inl" || b.type === "inr")
  )
    return a.type === b.type && valEq(a.val, b.val);
  return a === b;
};

export const evalWith = (tm: Tm, env: Val[]): Val => {
  switch (tm.type) {
    case "varT":
      return env[tm.index];
    case "unitT":
      return null;
    case "boolT":
      return tm.val;
    case "natT":
      return tm.val;
    case "uniqT":
      return UNIQ_LITERAL;
    case "pairT":
      return [evalWith(tm.fst, env), evalWith(tm.snd, env)];
    case "fstT":
      return (evalWith(tm.pair, env) as [Val, Val])[0];
    case "sndT":
      return (evalWith(tm.pair, env) as [Val, Val])[1];
    case "inlT":
      return { type: "inl", val: evalWith(tm.val, env) };
    case "inrT":
      return { type: "inr", val: evalWith(tm.val, env) };
    case "caseT": {
      const s = evalWith(tm.scrut, env) as { type: "inl" | "inr"; val: Val };
      // the branch binds the unwrapped value as Θ-var 0
      return s.type === "inl"
        ? evalWith(tm.onInl, [s.val, ...env])
        : evalWith(tm.onInr, [s.val, ...env]);
    }
    case "ifT":
      return evalWith(tm.cond, env)
        ? evalWith(tm.then, env)
        : evalWith(tm.else, env);
    case "primT":
      return applyPrim(tm.op, evalWith(tm.arg, env));
    case "strmT":
      // an obs-typed value is the body PAIRED with the environment, so
      // nothing is baked in and nothing has to be denotable as a term
      return { exp: tm.exp, env };
    case "nilT":
      return [];
    case "consT":
      return [evalWith(tm.head, env), ...(evalWith(tm.tail, env) as Val[])];
    case "foldT":
      // left fold; the step sees the element at 0 and the accumulator at 1
      return (evalWith(tm.list, env) as Val[]).reduce(
        (acc, x) => evalWith(tm.step, [x, acc, ...env]),
        evalWith(tm.init, env),
      );
  }
};

export const evalTm = (tm: Tm): Val => evalWith(tm, []);
export const applyFn = (fn: Fn, arg: Val): Val => evalWith(fn, [arg]);

// ---- unfoldMu: one unfolding of the μ knot ----
// Substitute the μ-var bound by this μ with the (closed) `mu body` node.
// The var starts in Δᵍ (guarded, unreferenceable); only a deferᵉ moves
// it into Δ, where a varE can name it — and it is always the OLDEST
// μ-var (highest index), so removing it never reindexes the others, and
// the substituted node is closed, so it needs no weakening.
type MuLoc =
  { where: "guarded"; idx: number } | { where: "usable"; idx: number };
type MuSt = { loc: MuLoc; gLen: number }; // gLen = |Δᵍ|

// under a nested μ: Δᵍ grows in front; a guarded target shifts up one
const muUnder = (st: MuSt): MuSt => ({
  gLen: st.gLen + 1,
  loc:
    st.loc.where === "guarded"
      ? { where: "guarded", idx: st.loc.idx + 1 }
      : st.loc,
});

// under a deferᵉ: Δᵍ empties and prepends onto Δ — a guarded target
// becomes usable at the same index; a usable one shifts by |Δᵍ|
const deferUnder = (st: MuSt): MuSt => ({
  gLen: 0,
  loc:
    st.loc.where === "guarded"
      ? { where: "usable", idx: st.loc.idx }
      : { where: "usable", idx: st.loc.idx + st.gLen },
});

const substMuTm = (tm: Tm, st: MuSt, knot: Exp): Tm => {
  switch (tm.type) {
    case "varT":
    case "unitT":
    case "boolT":
    case "natT":
    case "uniqT":
    case "nilT":
      return tm;
    case "consT":
      return {
        ...tm,
        head: substMuTm(tm.head, st, knot),
        tail: substMuTm(tm.tail, st, knot),
      };
    case "foldT":
      return {
        ...tm,
        list: substMuTm(tm.list, st, knot),
        init: substMuTm(tm.init, st, knot),
        step: substMuTm(tm.step, st, knot),
      };
    case "pairT":
      return {
        ...tm,
        fst: substMuTm(tm.fst, st, knot),
        snd: substMuTm(tm.snd, st, knot),
      };
    case "fstT":
    case "sndT":
      return { ...tm, pair: substMuTm(tm.pair, st, knot) };
    case "inlT":
    case "inrT":
      return { ...tm, val: substMuTm(tm.val, st, knot) };
    case "caseT":
      return {
        ...tm,
        scrut: substMuTm(tm.scrut, st, knot),
        onInl: substMuTm(tm.onInl, st, knot),
        onInr: substMuTm(tm.onInr, st, knot),
      };
    case "ifT":
      return {
        ...tm,
        cond: substMuTm(tm.cond, st, knot),
        then: substMuTm(tm.then, st, knot),
        else: substMuTm(tm.else, st, knot),
      };
    case "primT":
      return { ...tm, arg: substMuTm(tm.arg, st, knot) };
    case "strmT":
      return { ...tm, exp: substMuExp(tm.exp, st, knot) };
  }
};

const substMuExp = (exp: Exp, st: MuSt, knot: Exp): Exp => {
  switch (exp.type) {
    case "input":
    case "empty":
      return exp;
    case "varE":
      // the target is namable only once usable; it is the only var we
      // rewrite (inner μ-vars sit at other indices)
      return st.loc.where === "usable" && exp.index === st.loc.idx ? knot : exp;
    case "of":
      return { ...exp, items: exp.items.map((t) => substMuTm(t, st, knot)) };
    case "map":
      return {
        ...exp,
        fn: substMuTm(exp.fn, st, knot),
        src: substMuExp(exp.src, st, knot),
      };
    case "scan":
      return {
        ...exp,
        fn: substMuTm(exp.fn, st, knot),
        init: substMuTm(exp.init, st, knot),
        src: substMuExp(exp.src, st, knot),
      };
    case "take":
      return {
        ...exp,
        count: substMuTm(exp.count, st, knot),
        src: substMuExp(exp.src, st, knot),
      };
    case "mergeAll":
    case "switchAll":
    case "exhaustAll":
    case "batchSync":
      return { ...exp, src: substMuExp(exp.src, st, knot) };
    case "mu":
      return { ...exp, body: substMuExp(exp.body, muUnder(st), knot) };
    case "defer":
      return { ...exp, body: substMuExp(exp.body, deferUnder(st), knot) };
    case "mint":
      // mint extends Θ, not Δᵍ/Δ — μ-substitution state unchanged
      return { ...exp, body: substMuExp(exp.body, st, knot) };
  }
};

// body lives under one guarded μ-binder (Δᵍ = [t]); the knot is the
// closed `mu body` node substituted for the var it binds
export const unfoldMu = (body: Exp): Closed =>
  substMuExp(
    body,
    { loc: { where: "guarded", idx: 0 }, gLen: 1 },
    { type: "mu", ty: body.ty, body },
  );

// ---- Θ-index shifting: the renaming the smart constructors need ----
// Agda's `renTm` with a Θ-renaming. Indices at or above `cutoff` move
// up by `by`; below it they are bound locally and stay. A Tm reaches Θ
// through its Exp subterms too (strmT, and the Tms inside an Exp), so
// both walks are needed.

const shiftTm = (tm: Tm, cutoff: number, by: number): Tm => {
  const go = (x: Tm) => shiftTm(x, cutoff, by);
  switch (tm.type) {
    case "varT":
      return tm.index >= cutoff ? { ...tm, index: tm.index + by } : tm;
    case "unitT":
    case "boolT":
    case "natT":
    case "uniqT":
    case "nilT":
      return tm;
    case "consT":
      return { ...tm, head: go(tm.head), tail: go(tm.tail) };
    case "foldT":
      return {
        ...tm,
        list: go(tm.list),
        init: go(tm.init),
        step: shiftTm(tm.step, cutoff + 2, by), // element and accumulator
      };
    case "pairT":
      return { ...tm, fst: go(tm.fst), snd: go(tm.snd) };
    case "fstT":
    case "sndT":
      return { ...tm, pair: go(tm.pair) };
    case "inlT":
    case "inrT":
      return { ...tm, val: go(tm.val) };
    case "caseT":
      return {
        ...tm,
        scrut: go(tm.scrut),
        onInl: shiftTm(tm.onInl, cutoff + 1, by),
        onInr: shiftTm(tm.onInr, cutoff + 1, by),
      };
    case "ifT":
      return { ...tm, cond: go(tm.cond), then: go(tm.then), else: go(tm.else) };
    case "primT":
      return { ...tm, arg: go(tm.arg) };
    case "strmT":
      return { ...tm, exp: shiftExp(tm.exp, cutoff, by) };
  }
};

const shiftExp = (exp: Exp, cutoff: number, by: number): Exp => {
  switch (exp.type) {
    case "input":
    case "empty":
    case "varE":
      return exp;
    case "of":
      return { ...exp, items: exp.items.map((t) => shiftTm(t, cutoff, by)) };
    case "map":
      return {
        ...exp,
        fn: shiftTm(exp.fn, cutoff + 1, by),
        src: shiftExp(exp.src, cutoff, by),
      };
    case "scan":
      return {
        ...exp,
        fn: shiftTm(exp.fn, cutoff + 1, by),
        init: shiftTm(exp.init, cutoff, by),
        src: shiftExp(exp.src, cutoff, by),
      };
    case "take":
      return {
        ...exp,
        count: shiftTm(exp.count, cutoff, by),
        src: shiftExp(exp.src, cutoff, by),
      };
    case "mergeAll":
    case "switchAll":
    case "exhaustAll":
    case "batchSync":
      return { ...exp, src: shiftExp(exp.src, cutoff, by) };
    case "mu":
    case "defer":
      return { ...exp, body: shiftExp(exp.body, cutoff, by) }; // bind no Θ
    case "mint":
      // mint binds one Θ-var (uniqᵗ) — free Θ-vars inside the body are
      // above cutoff+1, so we shift with cutoff incremented by 1
      return { ...exp, body: shiftExp(exp.body, cutoff + 1, by) };
  }
};
