// The shared artifact: an untyped runtime mirror of Agda's Rx.Exp.
// Trees are DATA — generated by the prop-test generator, serialized to
// JSON for the Agda decoder, and compiled onto the real-rxjs
// primitives on this side.
//
// Well-typedness and μ-guardedness are NOT tracked by these types; the
// generator maintains them and the Agda decoder re-checks them. Every
// node carries its result Ty so that re-check is a local structural
// comparison, never inference.

// Agda: Rx.Exp.Ty
export type Ty =
  | { type: "unit" }
  | { type: "bool" }
  | { type: "nat" }
  | { type: "prod"; fst: Ty; snd: Ty }
  | { type: "sum"; left: Ty; right: Ty }
  | { type: "obs"; elem: Ty };

// Concrete stand-in for Agda's `PrimOp` postulate — the Agda side must
// become this exact datatype before the JSON bridge lands. Binary ops
// take a pair argument; sub is ℕ monus (truncated at 0).
export type PrimOp = "add" | "sub" | "mul" | "eq" | "lt" | "not";

// Agda: Rx.Exp.Val. unit = null. An obs-typed value is a CLOSED Exp —
// runtime observables are syntax, never host closures.
export type Val =
  | null
  | boolean
  | number
  | [Val, Val]
  | { type: "inl" | "inr"; val: Val }
  | Exp;

// Agda: Rx.Exp.Tm — first-order terms, the only function language.
// All variables are de Bruijn indices. Θ-binders (map/scan fns, case
// branches) bind their argument as varT index 0.
export type Tm =
  | { type: "varT"; ty: Ty; index: number } // into Θ
  | { type: "unitT"; ty: Ty }
  | { type: "boolT"; ty: Ty; val: boolean }
  | { type: "natT"; ty: Ty; val: number }
  | { type: "pairT"; ty: Ty; fst: Tm; snd: Tm }
  | { type: "fstT"; ty: Ty; pair: Tm }
  | { type: "sndT"; ty: Ty; pair: Tm }
  | { type: "inlT"; ty: Ty; val: Tm }
  | { type: "inrT"; ty: Ty; val: Tm }
  | { type: "caseT"; ty: Ty; scrut: Tm; onInl: Tm; onInr: Tm } // branches bind Θ-var 0
  | { type: "ifT"; ty: Ty; cond: Tm; then: Tm; else: Tm }
  | { type: "primT"; ty: Ty; op: PrimOp; arg: Tm }
  | { type: "strmT"; ty: Ty; exp: Exp }; // streams as values — how higher-order operators work

// Agda: Fn Γ Δᵍ Δ Θ s t = Tm with the argument bound as Θ-var 0.
export type Fn = Tm;

export type Exp =
  | { type: "input"; ty: Ty; index: number } // into Γ
  | { type: "of"; ty: Ty; items: Tm[] }
  | { type: "empty"; ty: Ty }
  | { type: "map"; ty: Ty; fn: Fn; src: Exp }
  | { type: "take"; ty: Ty; count: Tm; src: Exp } // count evaluated once, at subscription time
  | { type: "scan"; ty: Ty; fn: Fn; init: Tm; src: Exp } // fn's Θ-var 0 = pair(acc, cur)
  // NOTE: share is NOT an Exp node — share identity is a binding, not
  // an expression. Shared observables live in the slot telescope
  // (prop-test's Slot) and are referenced with `input`, exactly like
  // scripted inputs.
  | { type: "mergeAll"; ty: Ty; src: Exp }
  | { type: "concatAll"; ty: Ty; src: Exp }
  | { type: "switchAll"; ty: Ty; src: Exp }
  | { type: "exhaustAll"; ty: Ty; src: Exp }
  | { type: "mu"; ty: Ty; body: Exp } // binds a μ-var, GUARDED (Agda's Δᵍ)
  | { type: "varE"; ty: Ty; index: number } // into the μ-binder stack, usable vars only (Agda's Δ)
  | { type: "defer"; ty: Ty; body: Exp };
// ⚠ defer here is Agda's deferᵉ, NOT rxjs defer: lazy PLUS a one-tick
// hop, and the body's emissions mint fresh ids (an async boundary).
//
// μ-guardedness (Agda's Δᵍ/Δ split, enforced there by typing): a varE
// may only reference a mu binder if the path between them crosses at
// least one defer. Synchronous self-reference is invalid — generator
// invariant, re-checked by the Agda decoder.

// Agda: Closed Γ t — no free Θ-vars or μ-vars; input nodes are allowed.
export type Closed = Exp;

// Substitution plumbing — twins of Agda's evalTm/applyFn/unfoldμ,
// used by the rx compiler: evalTm/applyFn turn Tm functions into host
// functions for map/scan/take, unfoldMu ties the μ knot. (Agda's wkᵍ
// has no twin: with de Bruijn indices, weakening is the index shift
// performed inside unfoldMu.)
export declare const evalTm: (tm: Tm) => Val; // closed Tm only
export declare const applyFn: (fn: Fn, arg: Val) => Val;
export declare const unfoldMu: (body: Exp) => Closed; // substitutes (mu body) for the body's own bound var
