version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
    - task --list

  agda:
    dir: agda
    desc: compile/typecheck the agda source
    cmds:
    - agda src/Main.agda

  ts:
    dir: typescript
    desc: compile/typecheck the agda source
    cmds:
    - npm run start

  ts-check:
    dir: typescript
    desc: compile/typecheck the agda source
    cmds:
    - npm run typecheck
