-- STRATUM 2a of Verify-Budget-Sufficient: THE CAPS FACE (round 4).
--
-- Everything STATED IN TERMS OF the per-instant cap recurrence: the state
-- predicate capsOK?, the in-flight predicates (valCaps? / eventCaps? /
-- burstCaps? / obsCaps?), the frame face and the cascade companions,
-- caps-tick DERIVED from those, and the reachability cluster
-- (reach-resets) that pays round 3's debt.
--
-- THE SUBSCRIBE CLIQUE LEFT ON 2026-08-03, for .Subscribe-Face.  The
-- caps face itself (subscribeE-caps), the twelve companions mutual with
-- it, and the four delivery leaves that call it are a SUFFIX of this
-- module — reverse-reachability from the clique reaches nothing else
-- here, and stepFrame-FACE never calls stepFrame-CAPS — so they are now
-- a module of their own that imports this one public.  The ~45-clause
-- subscribe grind therefore re-checks 1.9k lines, not this file's 6.5k
-- (18 minutes cold).
--
-- THE RECURRENCE ITSELF LIVES IN .Caps as of 2026-08-01 — the Caps
-- triple, sizeStep / foldStep / iterSize / iterFold / frameStep /
-- frameBlowup with their monotonicity toolkit, capsAt, and the supply
-- lemmas that read a level off it.  .Wet reads those and nothing else
-- here, so with them inside this module every proof edit here re-checked
-- .Wet and Verify-Well-Formed for nothing.  This is the .Keeps-Ring
-- precedent applied a second time; see .Caps's own head.
--
-- THE ROUND-5 GATE IS STILL THE TYPE.  frameBlowup : Caps → Caps cannot
-- read the ledger, the receipt, or E, because they are not arguments.
--
-- This module is a SIBLING of .Wet, not a layer over it: the wet family
-- never mentions the caps FACE (checked), so the two are independent
-- extensions of .Caps and an edit here does not re-check the wet family.
--
-- Named Caps-Face rather than Caps because .Caps is now a real module and
-- the record it defines is named Caps.  It sits over .Caps, hence over
-- .Keeps-Ring, whose slotsEq is what transports a width bound across a
-- sub-call (valCaps? and its relatives read Sched.slots, and the caller
-- reports at the callee's post sched).
module Verify-Budget-Sufficient.Caps-Face where

-- Split 2026-08-12 into Caps-Face/Part1..Part7 to bound per-edit recheck
-- time (cold agda-dev was 72.6 s for the whole file).  All consumers
-- import this umbrella and are unaffected.
open import Verify-Budget-Sufficient.Caps-Face.Part7 public
