/**
 * The denotational model: an observable is a time-ordered list of emissions.
 *
 * A `Time` is a pair [tick, origin]. `origin` identifies the root cause of an
 * emission: a source subject, or a single `of` occurrence. Two emissions are
 * "simultaneous" exactly when their Times are equal — which, because distinct
 * origins never produce equal Times, can only happen when they trace back to
 * the same root cause (the diamond). This is the pair form of the
 * "timestamps are chosen points of an arithmetic sequence generated by the
 * provenance" scheme: ordering is lexicographic, i.e. the order induced by
 * the injection (tick, origin) -> tick * N + origin.
 *
 * Tick 0 is the subscription instant (where `of` values live, disambiguated
 * by origin); driver events get unique ticks >= 1.
 */
export type Time = readonly [tick: number, origin: number];

export const compareTime = (a: Time, b: Time): number =>
  a[0] !== b[0] ? a[0] - b[0] : a[1] - b[1];

export const timeEquals = (a: Time, b: Time): boolean =>
  a[0] === b[0] && a[1] === b[1];

export type TimedObs<A> = readonly (readonly [Time, A])[];

/** stable merge: on equal Times the left argument's emissions come first */
export const mergeTimed = <A>(a: TimedObs<A>, b: TimedObs<A>): TimedObs<A> => {
  const out: (readonly [Time, A])[] = [];
  let i = 0;
  let j = 0;
  while (i < a.length && j < b.length) {
    if (compareTime(a[i][0], b[j][0]) <= 0) {
      out.push(a[i++]);
    } else {
      out.push(b[j++]);
    }
  }
  return [...out, ...a.slice(i), ...b.slice(j)];
};

export const mapTimed = <A, B>(
  obs: TimedObs<A>,
  fn: (a: A) => B,
): TimedObs<B> => obs.map(([t, v]) => [t, fn(v)] as const);

export const takeTimed = <A>(obs: TimedObs<A>, count: number): TimedObs<A> =>
  obs.slice(0, count);

/**
 * The specification of batchSimultaneous: group consecutive equal Times.
 * (Equal Times are always adjacent in a merged list, since merge sorts.)
 */
export const batchSpec = <A>(obs: TimedObs<A>): TimedObs<A[]> => {
  const out: [Time, A[]][] = [];
  for (const [t, v] of obs) {
    const last = out[out.length - 1];
    if (last !== undefined && timeEquals(last[0], t)) {
      last[1].push(v);
    } else {
      out.push([t, [v]]);
    }
  }
  return out;
};

export const valuesOf = <A>(obs: TimedObs<A>): A[] => obs.map(([, v]) => v);
