-- THE PROBE TREE'S APPARATUS: the one module here that states no rows,
-- and the one `make evidence-check` reads as such by name.
--
-- THE TIE BETWEEN A RECEIPT'S ROWS AND THE STATEMENT THEY ARE EVIDENCE
-- ABOUT.  A probe used to restate its target's predicate by hand -- a
-- local `held d = regP? (λ p → …) …` -- and pin THAT by `refl`, so
-- nothing held the row to the postulate: a predicate mistyped, or one
-- quietly weaker than the statement's, stayed green and earned a
-- `PROBED:` receipt for a claim nobody had instantiated.
--
-- `Confirms` closes that.  It takes the target postulate APPLIED at the
-- probe's own concrete arguments and returns that application's type,
-- so the row's type is generated by Agda from the statement as it now
-- reads -- the probe cannot write the claim, only choose the point.
-- The argument is IRRELEVANT (the dot): it exists to fix the type and
-- can never be used, which is the point of passing the postulate at
-- all.  What inhabits the row is then whatever inhabits the statement
-- at that point, and `make evidence-check` (E7) refuses a body that
-- names a POSTULATE -- so the row stands on what this tower has proven,
-- and the statement it is evidence about cannot be its own witness.
--
-- THAT IS A LAUNDERING TEST AND NOT A COMPUTATION TEST, and the
-- difference is what makes the rule satisfiable at all.  A conclusion
-- denominated in a family this tower SEALS for cost does not reduce at
-- any point whatever, so a body held to a numeral could never be
-- written against one and the coverage could never be claimed.  A
-- weakening through a proven inequality does reach such a statement,
-- and is a stronger receipt than a numeral rather than a weaker one.
--
-- A sub-claim is reachable by the statement's OWN eliminators: project
-- a conjunct, apply a ∀ at a point, read a field of a record conclusion.
-- E7 requires the head under those eliminators to be a declared
-- `-- TARGET:`, since an arbitrary function applied to the postulate
-- could return any type at all and the tie would be gone.
module Probed.Apparatus where

Confirms : {A : Set} → .(claim : A) → Set
Confirms {A} _ = A
