-- THE PROBE TREE'S APPARATUS: the one module here that states no rows,
-- and the one `make evidence-check` reads as such by name.
--
-- THE TIE BETWEEN A RECEIPT'S ROWS AND THE STATEMENT THEY ARE EVIDENCE
-- ABOUT.  A probe used to restate its target's predicate by hand -- a
-- local `held d = regP? (λ p → …) …` -- and pin THAT by `refl`, so
-- nothing held the row to the postulate: a predicate mistyped, or one
-- quietly weaker than the statement's, stayed green and earned a
-- `PROBED:` receipt for a claim nobody had instantiated.
--
-- `Confirms` closes that.  It takes the target postulate APPLIED at the
-- probe's own concrete arguments and returns that application's type,
-- so the row's type is generated by Agda from the statement as it now
-- reads -- the probe cannot write the claim, only choose the point.
-- The argument is IRRELEVANT (the dot): it exists to fix the type and
-- can never be used, which is the point of passing the postulate at
-- all.  What inhabits the row is then whatever inhabits the statement
-- at that point, and `make evidence-check` (E7) holds the body to a
-- COMPUTED proof -- `refl`, `tt`, or a stdlib converter fed one -- so
-- the row can only be green because the claim evaluates to true there.
-- Handing the postulate itself back as the body is a type error on the
-- one side and a gate failure on the other.
--
-- A sub-claim is reachable by the statement's OWN eliminators: project
-- a conjunct, apply a ∀ at a point, read a field of a record conclusion.
-- E7 requires the head under those eliminators to be a declared
-- `-- TARGET:`, since an arbitrary function applied to the postulate
-- could return any type at all and the tie would be gone.
module Probed.Apparatus where

Confirms : {A : Set} → .(claim : A) → Set
Confirms {A} _ = A
