-- MAIN IS THE TOP-LINE PROOF (Anthony).  Three rules:
--
--   1. WHATEVER MAIN IMPORTS STICKS AROUND.  This list is the deletion
--      exemption — it is not a build convenience.  Everything else in
--      the repo exists only to serve one of these names, transitively,
--      and `make wiring` roots its reachability check right here.
--   2. NO BARE `open import`.  Individual definitions only, so that the
--      claim set is explicit and machine-readable rather than implied
--      by whatever a module happens to re-export.
--   3. MAIN IS NEVER TOUCHED WITHOUT ANTHONY'S EXPLICIT APPROVAL.
--
-- Note what is NOT here: `Verify-Well-Formed`.  It is machinery, not a
-- claim, and it is reached the honest way —
-- `formal-verification-batchSimultaneous` consumes
-- `evaluate-well-formed`, which consumes the run's two derivations.  If any part
-- of that tower is NOT reachable from a name below, that is a finding to
-- wire, not a reason to re-add a bulk import.
--
-- COVERAGE, and read this before trusting a green `make gate-heavy`: Agda
-- compiles exactly what is transitively imported, so this file defines
-- the build's coverage as well as its claim set.  Every module under
-- `agda/src` is currently reachable from a name below, which is what
-- `make wiring-gate` establishes in seconds and what makes a green heavy
-- gate a statement about the whole tree rather than about whichever part
-- of it this list happens to reach.
module Main where

------------------------------------------------------------------
-- THE THEOREM.  The verified object, end to end: for every program,
-- batching its rendered stream is spec-correct.
------------------------------------------------------------------
open import Verify-Batch-Simultaneous.The-Proof
  using (formal-verification-batchSimultaneous; batch-agreement)

open import Verify-Batch-Simultaneous.Batch-Theorems
  using (batch-online)

------------------------------------------------------------------
-- THE README'S SEMANTICS.  Each is a claim about a canonical program named
-- in `agda/README.autogenerated.md`; the programs themselves are consumed by
-- these claims and so need no separate mention.
------------------------------------------------------------------
open import Readme-Theorems
  using (readme-batch-order-is-delivery-order
        ; readme-take-counts-values
        ; readme-one-subscribe-one-batch
        ; readme-diamond
        ; readme-each-next-own-instant
        ; readme-cascades-inherit
        ; readme-completion-cascades
        ; readme-share-connect-no-replay
        ; readme-late-join-growth
        ; readme-serial-joins-mirror-rxjs)

------------------------------------------------------------------
-- THE EVALUATOR-LEVEL CLAIMS.
--
-- CAUTION, recorded here because Main is where it will be read:
-- `causality` is stated over `truncateIn`/`emittedBefore`, which are
-- POSTULATED functions, so it is currently satisfiable by instantiating
-- `emittedBefore k = []`.  `defer-shift` is still `⊤`-typed — an emit
-- carries `instant : Id` but no `Tick`, so its claim is not statable
-- without new machinery (see that module's header).  `μ-guarded`'s type
-- is syntactically IDENTICAL to `μ-unfold`'s despite its comment
-- claiming a distinct bound.  All three are listed anyway: they are
-- claims we intend to make, and hiding them would shrink the ledger
-- without shrinking the debt.
open import Rx.Evaluator-Theorems
  using (fuel-coherent; causality; μ-unfold; μ-guarded; defer-shift)

open import Rx.Provenance-Theorems
  using (id-inheritance)

------------------------------------------------------------------
-- TAKE BOUNDS THE STREAM.  Claimed here because it has no consumer and
-- is not meant to acquire one: it is a rehearsal of the drain
-- induction, chosen so that the machinery it exercises is the
-- well-formedness face's while the statement needs none of that face's
-- apparatus to mean something.
------------------------------------------------------------------
open import Verify-Take-Bounds
  using (take-bounds-values)

------------------------------------------------------------------
-- THE RUN RELATION IS A FUNCTION.  Claimed here rather than by a
-- consumer, because its consumers are the claims that build their own
-- derivations and none of those is written yet — and because a claim
-- that needs it typechecks without it while proving something weaker
-- than its own name, which is the one shape a missing fact does not
-- announce.
------------------------------------------------------------------
open import Verify-Determinacy
  using (evaluate-deterministic)

------------------------------------------------------------------
-- WHAT A PROGRAM MEANS, AND THAT THE MACHINE COMPUTES IT.  Claimed
-- here rather than by a consumer for the same reason determinacy is:
-- every face below is stated over the machine's own output, so none of
-- them needs a denotation to typecheck, and a semantics stated only
-- when its first consumer arrives is a semantics that consumer's
-- author has to invent.
--
-- CAUTION, and it is the same shape as the timing claims': `adequacy`
-- and `saturation` are stated over a POSTULATED domain (`Beh`,
-- `denote`, `observe`), so what they pin today is the limit of the
-- machine rather than a compositional reading of the syntax.  Listed
-- anyway, on the same reasoning: they are claims we intend to make, and
-- hiding them would shrink the ledger without shrinking the debt.
-- `run-monotone` is the exception — it mentions nothing postulated and
-- a program can refute it.
------------------------------------------------------------------
open import Verify-Adequacy
  using (run-monotone; adequacy; saturation)

------------------------------------------------------------------
-- THE TIMING CLAIMS.  CAUTION: all three are stated over nine
-- postulated abstract helpers in the same module (`Node`, `NodeSt`,
-- `Inbox`, `inboxOf`, `stAt`, `cascade`, `δ`, `Retiming`, `retime`),
-- so as written they are close to vacuous — those helpers must become
-- definitions before these assert anything.
------------------------------------------------------------------
open import Rx.Time-Theorems
  using (locality; non-interference; timing-invariance)
