-- README SEMANTICS THEOREMS — `agda/README.autogenerated.md`'s semantics-by-edge-case,
-- each a top-line result stated against the spec (ported from v1, where
-- all ten were proven).  A statement that will not prove is a drift
-- between the README and the Agda spec: exactly what this file catches.
--
-- Two universal laws over the whole grammar.  They compare only
-- VALUES (emitValues) — ids and protocol traffic are the other theorem
-- files' business.
--
-- AND THE QUANTIFIED INSTANCES ARE NOT HERE, BECAUSE THEY WERE WRITTEN
-- AT THE WRONG TREE (Anthony).  Each was a plain `Exp` program driven
-- by a scripted slot, and a plain program's run carries no envelope at
-- all, so there was nothing for the batcher to group: the statements
-- named a shape the plain tree cannot express rather than a fact that
-- had stopped holding.  Restating them means writing them as `SExp`
-- programs under `elaborate`, which changes what each one says, so they
-- are owed where the simul tree is worked and not here.
-- RECOVERY: git show 5f84ffe3:agda/src/Readme-Theorems.agda restores
--   all seven, with the `mergeOf`/`hotOnce`/`oneSlot`/`twoHots` slot
--   shorthands and the `growthCtx` telescope they ran against; the same
--   sha's `Rx/Exp.agda` holds `evalTm` and `applyFn`, the closed-term
--   wrappers their expected sides were written in, which nothing else
--   consumed and which are one line each over `evalWith`.
-- RECOVERY: git show 54227c28:agda/src/Readme-Theorems.agda restores
--   `readme-take-counts-values`, the take law, whose statement stands
--   over `Rx.Elaborate`'s `takeᵖ` -- the level shift the law exists to
--   name.  It is owed where the simul tree is worked, as an `SExp`
--   program under `elaborate` rather than at the plain tree it was
--   written at.
module Readme-Theorems where

open import Data.Nat     using (_≤_)
open import Data.List    using (List; []; _∷_; _++_; concat; length)
open import Data.Vec     using ([]; _∷_)     -- contexts are Vecs; ∷/[] overload per type
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Rx.Prim      using (Fuel; InstEmit; _at_from_as_)
open import Rx.Exp       using (Ctx; Closed; uniqᵗ)
open import Rx.Envelope  using (instEmitᵗ)
open import Rx.Envelope.Decode using (decodeStream)
open import Rx.Evaluator.Builder using (evaluate↓)
open import Rx.Slots using (Slots)
open import Spec         using (spec-batchSimultaneous; valuesOf)

------------------------------------------------------------------
-- projections: a stream's values in delivery order (at A this is
-- the raw value stream; at List A, each batch's value list)
------------------------------------------------------------------

emitValues : ∀ {A : Set} → List (InstEmit A) → List A
emitValues []                     = []
emitValues ((es at _ from _ as _) ∷ xs) = valuesOf es ++ emitValues xs

------------------------------------------------------------------
-- THREE UNIVERSAL LAWS (over the whole grammar)
------------------------------------------------------------------

postulate
  -- Batch order is delivery order.  The flagship: batching only
  -- GROUPS — never reorders, never drops.  MergeAlling the batches
  -- recovers the raw value stream, for every program and driver.
  -- PROBED: `Probed.Readme-Claims`, at a two-value elaborated source in
  --   an empty slot table.  LOAD-BEARING on order and on completeness
  --   both -- the values differ, so a swap or a drop fails the `refl`.
  --   Not reached: anything the probe file's own header records as
  --   unreachable, which is every flattening program.
  readme-batch-order-is-delivery-order :
    ∀ {n} {Γ : Ctx n} {u} (fuel : Fuel)
      (e : Closed Γ (instEmitᵗ uniqᵗ u)) (ins : Slots Γ) →
    concat (emitValues (spec-batchSimultaneous
                         (decodeStream (evaluate↓ fuel e ins))))
      ≡ emitValues (decodeStream (evaluate↓ fuel e ins))

  -- One subscribe() call is one batch.  Fuel 0 runs only the
  -- subscribe frame — a single instant — so ANY program, however
  -- wired, yields at most one batch.  (Strictly stronger than v1's
  -- source-free version: arrivals cost fuel, defers included.)
  -- PROBED: `Probed.Readme-Claims`, at an elaborated source whose
  --   subscribe frame emits, so the bound is met at ONE rather than
  --   vacuously at zero.  Not reached: a program whose subscribe frame
  --   emits nothing, and every flattening program.
  readme-one-subscribe-one-batch :
    ∀ {n} {Γ : Ctx n} {u} (e : Closed Γ (instEmitᵗ uniqᵗ u)) (ins : Slots Γ) →
    length (spec-batchSimultaneous (decodeStream (evaluate↓ 0 e ins))) ≤ 1
