------------------------------------------------------------------
-- THE EVALUATOR NEVER GETS STUCK: no run of any program emits the dry
-- marker.
--
-- `evaluate` descends on an accessibility witness, and three of its
-- clauses are guarded by a decidable comparison that can fail — the
-- share connect's unconnected count, the inner subscribe's rank, the μ
-- unfold's syncSize.  A failing guard is not an error: the clause
-- returns a `dry` emit and the run continues, so exhaustion is VISIBLE
-- in the output rather than fatal.  This says the guards never fail at
-- the triple the evaluator actually enters at, which is what makes the
-- descent discipline invisible to every statement above it.
--
-- IT IS THE WHOLE OF WHAT THE DESCENT COSTS, and stating it in one line
-- is the point.  Its type mentions no witness, no triple and no order:
-- `evaluate` builds its own entry out of the program and the telescope,
-- so every consumer sees a total function on `Fuel`, and this is the
-- only place that entry has to be shown adequate.  A statement anywhere
-- above that had to know which triple a subterm runs at would be a
-- statement the descent had leaked into.
--
-- WHAT IS OWED IS TWO LEAVES, AND THEY SPLIT THE RUN RATHER THAN THE
-- THREE GUARDS.  A run is the root subscribe followed by the drain, and
-- the subscription walk's own dry-freedom is proven clause by clause in
-- `Verify-Rank-Sufficient.Dry` — both settled peels included, each as
-- the `no` arm of the machine's own decision, refuted out of the entry
-- invariant.  What is left is the OPERATOR SHELF, where the walk holds
-- its witness fixed and re-enters through a burst, and the DRAIN LOOP,
-- which is every arrival after the first frame.  Neither is a guard
-- reading: nothing goes dry at a `mapᵉ` node or at a schedule pop, so
-- what the two of them wait on is dry-freedom of the burst pipeline —
-- one induction over a different family, and where the rank peel is
-- spent.
--
-- THE RANDOM SWEEP REACHES THE REGION, and that is a number rather than a
-- claim.  `QuickCheck` emits `μᵉ`, `varᵉ` and `deferᵉ` with the binder
-- scopes carried as INDICES, so a synchronous self-reference is not a
-- program it can write down and be rejected for; and its recursion is
-- linear by grammar, since a body reading its own var twice respawns per
-- tick and real rxjs hangs on that program too.  Every case reads `hasDry`
-- off the run, so a failing seed is now a counterexample to one of the two
-- leaves rather than to anything stated here.  Twenty seeds at depth four
-- and five at depth five — 4500 programs, a third of them carrying a live
-- recursion — report no dry run.  IT IS MEASURED, NOT RECHECKED: a
-- compiled binary's row discharges nothing, and what it buys is the
-- coverage doubt, which was that the three peels had been reached only at
-- shapes one author chose.
------------------------------------------------------------------
module Verify-Rank-Sufficient where

open import Data.Bool using (false)
open import Data.Nat using (z≤n)
open import Data.Product using (_×_; proj₁; proj₂)
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Rx.Prim  using (Fuel; Id)
open import Rx.Exp   using (Ctx; Closed)
open import Rx.Slots using (Slots)
open import Rx.Evaluator using (Stream; Sched; EvalSt; evaluate; drain; hasDry;
  subscribeE; rootWitness; root; sched-init; st-init)
open import Verify-Rank-Sufficient.Dry using (subscribe-dry-free)
open import Verify-Rank-Sufficient.Dry-Emits using (hasDry-++)
open import Verify-Rank-Sufficient.Entry using (rootTri-reads)
open import Verify-Rank-Sufficient.Hop using (hopFits)

-- THE THREE PEELS ARE NOT THREE GRINDS OF ONE SIZE, AND THE ASYMMETRY IS
-- THE SCHEDULE OF THIS TIER.  Two of them are one line over a fact about
-- SYNTAX, and the evaluator's own guard is the statement: the μ peel wants
-- the unfolded body's syncSize under the size it entered at, which is the
-- order's μ constructor applied to an unfold equation; the connect peel
-- wants the unconnected count to drop when a fresh share joins the
-- connected list, which is the order's connect constructor applied to an
-- insertion lemma, under a freshness premise the machine establishes for
-- itself before the clause fires.  The RANK peel's own ≺-witness is the
-- hop constructor handed its own hypothesis and so says NOTHING — every
-- gram of that reading is establishing the hypothesis.  That prediction is
-- now confirmed rather than argued: the two cheap peels landed as the
-- walk's own arms, and what is left open is exactly the third.

-- NOTHING HERE IS CIRCULAR, which was the standing doubt against replacing
-- a counter with an order.  Of the three peels only the rank one asks what
-- a RUN did.  The μ peel reads its own body, an equation on syntax; the
-- connect peel reads the slot telescope, which is unchanged across a run,
-- so its premise is an equation too rather than an invariant something has
-- to preserve.  Neither settled peel needed the descent to have gone well
-- in order to say that its own edge drops.  What both needed is the entry
-- invariant — that the triple the evaluator stands at reads the term it is
-- about to subscribe — and that is why the invariant was the thing to
-- state first and the peels were its cheap arms.

-- THE RANK READING'S SHAPE IS A STRENGTHENING RATHER THAN A FOURTH
-- MEASURE, and that is the plan for the one leaf still open.  The inner is
-- a runtime VALUE — an observable a sibling call emitted — structurally
-- unrelated to the term the caller was subscribing, so no equation on
-- syntax reaches it.  What does reach it is where it came FROM: it rode a
-- burst some subscribe produced, so its nesting can travel as a
-- strengthened RETURN TYPE on the burst-producing functions, invariant in
-- the motive, rather than as a measure nobody has.  Ordinary induction,
-- and the thing to get right is the strengthening and not arithmetic.
--
-- AND THERE IS NO LONGER A SECOND QUANTITY TO COMPARE AGAINST, which is
-- what the strengthening is FOR.  The entry's rank IS the hop reading, so
-- the peel and the thing it peels are denominated alike and the whole of
-- what is owed is that an emitted inner reads under its emitter.  Every
-- route this row used to describe was an attempt to relate two currencies
-- — a counter over SYNTAX against growth a RUN produces — and each died
-- the same way, the run multiplying where the seed merely doubled.
--
-- DEAD ROUTE: a rank SEEDED off the term, in every form it was tried:
--   a power of two in the program's syntactic size plus the slot
--   telescope's, at each entry, and the additive
--   candidates before it.  A seed grows with the SYNTAX while what has
--   to be dominated is what the run DELIVERS, which a fold multiplies
--   once per delivery; and a size seed cannot survive the μ clause at
--   all, since an unfolding is larger than its redex while the witness
--   keeps its rank.  `Refuted.Sync-Count` is where the last additive
--   candidate for that currency died.
-- DEAD ROUTE: the apparatus of the generation this argument was
--   recovered from — a FOLD of the triple into one ℕ, and the caps
--   feeding it.  It existed so a counter could dominate the order
--   structurally; this evaluator descends on the order ITSELF, so there
--   is nothing for a fold to dominate.  Its rows are a lead to read,
--   never a statement to cite: the currency moved too, that generation
--   carrying a hop DEPTH under its own cap, which answers a different
--   question from a rank that peels one per hop.

-- THE DRAIN IS THE SECOND HALF OF A RUN AND THE HALF THAT RECURSES.  The
-- root subscribe returns one burst and a schedule; everything after it is
-- this loop pulling one arrival at a time and cascading it to quiescence,
-- so every unfolding past the first, every later connect, and every
-- emitted inner is reached from in here.  The loop's OWN recursion owes
-- nothing — it descends on `Fuel`, and the cascade underneath it descends
-- on the telescope position, a premise a shared slot carries in its own
-- type — so what this leaf is about is the guarded peels a cascade
-- re-enters through, and not the descent of either loop.
--
-- AND THE SCHEDULE AND THE STATE ARRIVE UNCONSTRAINED, WHICH IS A GAP AND
-- NOT A GENERALITY.  Both are universally quantified here and nothing in
-- the hypotheses relates either to `e`.  The STORE half of that costs
-- nothing now: the cascade re-seeds per ARRIVAL rather than off the root,
-- and `arrivalWitness` enters at the value's nesting joined with
-- `stHop`, so a registry no run could have built is bounded by the same
-- expression as one a run produced, and the arbitrary store is a
-- generality after all.  What no seed reads is what happens AFTER it is
-- minted: one arrival's chain fold can deliver many times, a fold
-- deepens its accumulator by the step's own reading per delivery, and the
-- entry was taken once.  Whether that ever reaches the dry close is the
-- question the operator leaf answers YES to from the other side, and it
-- is the one this row could not put until a cascade had been
-- instantiated rather than argued about.

-- AND THE PREMISE IS NOT AN INVARIANT, WHICH CONSTRAINS THE TICK-GATING
-- ARGUMENT ABOVE RATHER THAN THE CONCLUSION BELOW.  That argument says a
-- single entry need only cover what a term produces SYNCHRONOUSLY, since
-- a recursion re-enters through a gate whose body is pending at the next
-- tick.  What it misses is that a GATE'S OWN OPENING IS A REGISTRATION: a
-- defer installs a flattening frame and leaves its body pending, so the
-- frame outlives the subscribe that made it, and a chain carries one
-- flattening edge for each flattener whose OUTER SOURCE is still live
-- along it.  Nesting flatteners over DATA stacks nothing — an inner
-- attaches BELOW the frame, which the chain measure passes through at
-- zero — so the one shape that stacks them is a flattener whose outer is
-- a gate.  And the reading cannot see that stack, because its gate clause
-- is CONSTANT: it prices a defer at one without descending, which is the
-- clause that buys the descent its recursion edge.  Tick-gating is
-- therefore what OPENS the gap rather than what closes it, and one more
-- turn of the same crank adds one to the chain and nothing to the term.
--
-- SO WHAT IS DEAD IS THE ROUTE AND NOT THE STATEMENT.  Every program
-- exhibiting this runs dry-free, so the leaf may well be true; what
-- cannot be done is to reach it by an induction that carries this
-- premise, since the premise holds TIGHTLY at entry and is destroyed by
-- the FIRST arrival.  Nor is the repair local: charging a gate's body
-- would close it and would cost the descent the edge the constant clause
-- exists to buy, so this is the tier's open question — whether one
-- reading can price what no frame hands the next one — arriving at the
-- premise rather than at the conclusion.
--
-- AND THE RIGHT-HAND SIDE CANNOT BE WIDENED TO REACH IT, WHICH IS WHAT
-- NARROWS THE QUESTION.  The run does hold the missing reading, for
-- exactly as long as it is useless: a gate's body waits in the
-- schedule's pending list, and its reading there IS the figure the
-- registry reaches one arrival later, at both witnesses.  The arrival
-- that installs the frame is the arrival that consumes the entry
-- predicting it, so the join of the term, the store and the schedule
-- reads the same as the term alone one step on.  The quantity is
-- HISTORICAL: no reading of any single state is preserved, so the
-- repair is not a bigger bound.  Either it is CARRIED — a maximum over
-- the run so far, which is the shape this tower exists to have left
-- behind — or this premise should not exist and what must be adequate
-- is the rank each ARRIVAL enters at, which the machine already
-- re-seeds and which is a different statement.

-- AND THE CASCADE DOES NOT OUTGROW ITS ENTRY, WHICH IS WHY THIS ROW IS
-- NOT THE OPERATOR ROW UNDER ANOTHER NAME.  A cascade is ONE INSTANT,
-- and both axes a term does not read are tick-gated: an arrival is a
-- tick by construction, and a recursion re-enters only through
-- `deferᵉ`, whose body is pending at `suc now`.  So what a single entry
-- has to cover is the deliveries a term can produce SYNCHRONOUSLY — and
-- a fold's reading gains one layer per delivery while the seed doubles
-- per symbol of the term producing them.  Linear against exponential in
-- the one parameter that moves both, which is the same shape the
-- arrival rows found ACROSS entries; so the denomination the paragraph
-- above asks for is the seed the machine already mints, and what is
-- left in this row is the unconstrained schedule alone.
--
-- AND WHAT LICENCES THE HYPOTHESIS IS THAT THE UNCONDITIONAL FORM IS
-- FALSE, WHICH IS THE ONLY THING THAT DOES.  Adding one otherwise
-- trades tracked debt for untracked debt, so a statement that might
-- still hold outright may not acquire one — and the two witnesses below
-- close that off, the second of them against the obvious weaker repair.
-- `hopFits` is the quantity they say is absent:
-- a chain's own remaining-hop content, read off the very frames the
-- witness exploits, against the reading of the program those frames
-- belong to.  Its environment is the schedule's OWN — `slotRd` at the
-- schedule's telescope — so no caller may soften it by choosing a
-- reading nobody runs; and both sides compute, which makes this
-- refutable at a concrete registry rather than merely unproven.
--
-- AND THE PREMISE'S LEFT SIDE REPLAYS THE RIGHT ONE ALONG THE CHAIN,
-- WHICH IS WHAT LEAVES THIS ROW WITH EXACTLY ONE SUBJECT.  The chain
-- measure hands each frame the reading the frame above it produced and
-- spends the term reading's own step at every one, so the two sides
-- cannot part on a chain the entry built — they are the same
-- arithmetic walked in the same order.  What can part them is a frame
-- the term never produced, which is precisely a chain a cascade has
-- lengthened past the program that built it, and that is the region
-- this leaf is about.
--
-- REFUTED: `Refuted.Drain-Reachable` — the form as written, at a store
--   whose root term is the EMPTY observable.  A chain is a `Path` typed
--   by the context and the root type alone, so it carries no index
--   tying it to the program; a `map-f` frame applies whatever function
--   the registry's author wrote, and `foldPath` threads ONE witness
--   through every frame without re-seeding at any of them.  A plain
--   numeral arrives at nesting zero, a store whose only node holds an
--   empty queue adds zero, and the frame hands back a tower the
--   `thru-outer` behind it then subscribes.  The gap is not a rate: it
--   is unbounded at every seed, since the tower is written one level
--   deeper at no cost to any quantity the entry reads.
-- REFUTED: `Refuted.Drain-Reachable` — and the same witness kills the
--   form CONDITIONED on the coherence record, which is what says the
--   repair is not a hypothesis.  Every field is satisfied at that
--   state: the counts agree, the element types gate the one entry in,
--   the protocol sits at its initial watermark with no open instant,
--   the merge node's counter matches a chain contributing no inner
--   instance, and an empty context has no hot slot to keep live.  The
--   record constrains the registry's COUNTS and TYPES, while the depth
--   is a property of a chain's FRAMES — so what is missing is a tie
--   between a registration's frames and the program being run, which
--   has no home in the record as it stands.
-- REFUTED: `Refuted.Fit-Cascade` — the fit's PRESERVATION across one
--   cascade, taken through the drain's own step so the pair is the one
--   the recursion would have been handed.  A flattener over a gate,
--   behind a second gate, over a slot whose values all arrive late:
--   carried one against a term reading of one at the door, carried TWO
--   against the same one after a single arrival.  Strip the outer gate
--   and the reading is EXACT at the same states — two against two, three
--   against three — which rules out the chain manufacturing depth and
--   rules out the arithmetic being wrong, and leaves the one clause that
--   declines to look.  The deeper witness reads three against one, so the
--   gap is a rate in the program's own size rather than an off-by-one,
--   and both programs' dry rows are pinned beside the crossings so the
--   finding cannot be read one statement too high.
-- REFUTED: `Refuted.Fit-Cascade` — and the same witness kills the
--   WIDEST state-readable bound, which is what says the repair is not a
--   larger right-hand side.  Joining the store and the schedule's
--   pending bodies to the term holds at the door and holds for the
--   right reason — the pending reading is two and three there, exactly
--   the figures the registry reaches one arrival later — and one step
--   on both the store and the pending read ZERO against a registry
--   still carrying the frame.  So the quantity is historical rather
--   than a property of any state, and a wider join cannot recover it.
-- REFUTED: `Refuted.Arrival-Seed` — the third candidate, and the one with
--   the best claim: the rank an ARRIVAL enters at, which is a SUM rather
--   than a join, so the arithmetic killing the join does not touch it and
--   it is what the chain fold actually descends on.  It has room at the
--   door on both programs — three against one, four against one, because
--   the payload about to arrive reads deep — and one arrival later BOTH
--   variable summands read ZERO, the payload spent and the flattener's
--   queue empty, so the seed collapses onto the term's own reading while
--   the registry keeps the frame the arrival installed.  The deeper
--   program reads three against the same one, so this gap is a rate too.
-- REFUTED: `Refuted.Arrival-Filtered` — and the narrowing the dead route
--   below was read as forbidding, tested rather than assumed: the chains
--   ONE arrival reaches, priced against the value that arrival actually
--   carries, which is the smallest left side a drain step could justify
--   and is strictly under the one above.  It holds EXACTLY at both doors —
--   three against three, four against four — and crosses one arrival later
--   at the same two states, because neither narrowing does any work there.
--   The filter reaches ONE chain and it is the deep one; the arriving value
--   reads ZERO, so the seed is the floor.  Those two rows are the content:
--   they say the information a step has over a state is not the missing
--   information, which no reading of the registry could have shown.
-- DEAD ROUTE: BOUNDING THE REGISTRY IS THE DEAD MECHANISM, NOT ANY ONE OF
--   THE STATEMENTS ABOVE.  Four successive candidates for what
--   holds at a drain step — the term's reading, the widest state-readable
--   join, the arrival's own seed, and the step's own filtered spend — are
--   each refuted at the same two
--   programs, and the fourth is a sub-case of the third rather than a
--   smaller region, so the sequence has stopped subdividing and started
--   confirming.  The mechanism is
--   wrong because the registry prices what a chain COULD spend given an
--   arbitrarily deep value, and no state carries what value will arrive;
--   a fold spends what the value it is HANDED makes it spend.  So a
--   fourth reading of the registry is not the repair, and the premise is
--   owed to the frame shelf that already states its obligations per
--   template, against the payload each one is given.
-- PROBED: `Probed.Descent` — twelve recursive programs, every one green,
--   taken against the DRAIN of each run rather than the whole of it.  What
--   they cover, guard by guard: the μ peel at every program, since all
--   twelve are `μᵉ` and the drain is where the unfolding repeats; the
--   connect peel at the five carrying a slot, `shared` and `scripted`
--   both, one of them a diamond reaching the share twice in an instant;
--   and the RANK peel at the recursive self-reference, which is an emitted
--   inner that unfolds to its own emitter, at μ nested directly in μ, and
--   at a share holding a recursion — the shape whose nesting the guard
--   cannot read off the term it compares.  Each row pins its drain's EVENT
--   COUNT beside it, so none is `false` by an empty stream.  THE BOUNDARY:
--   one fuel, hand-written programs, μ nested two deep and no deeper.
--   These rows are `refl` pins and buy exactly the twelve shapes they
--   name, which is why the coverage past them is bought by an instrument
--   that is not a pin.
-- PROBED: `Probed.Fuel-Growth` — six drains of ONE run, differing in
--   FUEL alone, at a fold whose source is a recursion, so how many
--   arrivals happen is the drain's business and not the term's.  Both
--   readings of the term hold still across the six while the carried
--   hop reading is the fuel plus one: the rate is ONE per arrival,
--   exactly, and it is the quantity an arrival's own entry reads.  The
--   term reads 3 there, so the rows OVERTAKE it at three units and the
--   leaf is still green at six, where the run's output reads more than
--   twice what any reading of its program could give.  THE
--   BOUNDARY: one delivery lands per arrival, so every layer the rows
--   count is paid for by a fresh entry and none of them reaches a burst
--   delivering many times inside one cascade — a region `Probed.Entry-Fit`
--   reaches for the DOOR, at twenty-four deliveries under one arrival,
--   but which no row here or there carries into this leaf's own drain.
-- PROBED: `Probed.Fit-Preserved` — the fit at states the DRAIN produced,
--   which every receipt above is silent about.  `stepOnce` is the loop's
--   own step with the emit stream dropped — the same pull, the same
--   cascade, the same instant counter — so a row reads the pair the
--   recursion would have been handed rather than one written by hand.
--   Nine rows over three recursive programs at one, two and three
--   arrivals, each spending the decision procedure on the comparison, so
--   a fit the k-th arrival destroyed leaves its row unsolvable instead of
--   letting it through.  The finding is stronger than preservation: the
--   carried reading does not MOVE — one at all twelve states, against
--   term readings of one, two and three — while the registration counter
--   climbs at every step on every program, which is what separates a flat
--   reading from a stepper that had become a fixed point.  And the
--   plainest program is TIGHT, one against one, so a registry carrying a
--   single hop more would fail outright and the flat rows are taken where
--   the statement is closest to false.  THE BOUNDARY: three arrivals, a
--   merge only, and nothing here reaches the late-slot cascade the
--   receipt above instantiates.
-- PROBED: `Probed.Drain-Arrival` — the boundary both receipts above name,
--   which is the same one from opposite sides: many deliveries inside ONE
--   cascade, carried PAST the arrival rather than read at the door.  Six
--   and twenty-four deliveries per arrival, plus a family where every one
--   of them installs a registration still live when the cascade ends.  The
--   fit holds at all seven reached states and the carried side does not
--   MOVE — two, two, two; two, two, two; three at all four — while the node
--   counter climbs 2, 3, 4, 5 and the registration counter 1, 7, 13, so a
--   stepper gone quiet is ruled out separately.  The finding is which side
--   the region's own axis moves: lengthening the burst takes the TERM
--   reading from 19 to 73 and leaves the registry at two, because a fold
--   reads its source's delivery count as its refold count.  Delivery count
--   inflates the bound rather than the quantity bounded, so this region is
--   not where the risk is.  THE BOUNDARY: no row is TIGHT and none can be,
--   the parameter defining the region being the one widening the margin —
--   a tight row has to hold the deliveries fixed and deepen the registry
--   instead.  Three arrivals, one slot, one flattening strategy.

postulate
  drain-dry-free : ∀ {n} {Γ : Ctx n} {t} {e : Closed Γ t}
    (fuel : Fuel) (nextId : Id)
    (sched : Sched Γ) (st : EvalSt e) →
    hopFits sched st →
    hasDry (drain fuel nextId sched st) ≡ false

-- THE FIT AT THE DOOR.  `evaluate` hands the drain the state its root
-- subscribe left, so this is the one arrival-free instance the
-- assembly needs, and it is a leaf rather than a hypothesis because
-- nothing above it is free to choose the state.  It takes no fuel: the
-- entry state is what the subscribe frame produced, and the drain has
-- not run yet.
--
-- REFUTED: `Refuted.Hop-Sum` — the predecessor CHAIN measure, which
--   read every frame's template apart and added.  The repair was on the
--   measure's own side — a reading threaded down the chain — and every
--   row below survived it, which is what the witness is named here for:
--   it pins WHICH measure this statement is about, and a return to the
--   summing one puts the crossing straight back.
-- PROBED: `Probed.Entry-Fit` — the SCRIPTED slot, which is where this
--   statement was once false: a slot's reading has three components,
--   two of them forced to zero by `isData`, so the count is the only
--   one that can be got wrong and it is the one that reaches the hop —
--   through the flattener's product and then through a fold, which
--   spends the product as its refold count.  A count taken at the
--   subscribe frame reads zero at a source whose values all arrive
--   late, and the chain above it collapses with it.  The rows sit at
--   exactly that slot and the term side now reads 7 against a registry
--   of 2, with the margin WIDENING out to twenty-four deliveries under
--   one arrival.  And they do not stop at programs whose deliveries the
--   term counts, which would be circular: six cascades of a fold over a
--   RECURSION, stepped by the loop's own step, at the one program whose
--   output is known to outgrow every reading of itself.  THE BOUNDARY:
--   one slot, and no HOT one — a hot source is anchored at tick zero
--   rather than at the subscription, so its clause over-approximates
--   and a row there would instantiate something weaker than these do.
--   AND ONE ROW IS TIGHT, which none of those can be made: two
--   templates that never mention what they are handed, each an
--   observable one flattener deep, under a third.  That is the shape a
--   chain measure reading its frames APART crosses the term at, and it
--   lands on the nose — 2 against 2 — so the region where the two
--   sides can disagree at all is instantiated rather than argued.  The
--   figures every other row here pins were taken against the summing
--   predecessor and came back UNCHANGED, which is what says the
--   coverage above is about the measure as it now reads.
-- PROBED: `Probed.Descent` — the root entry of three recursive
--   programs, each a `refl`-free row whose witness is the decision
--   procedure on the comparison itself, so a premise FALSE at the
--   point would leave the row's implicit unsolvable rather than let it
--   pass.  The three are plain recursion, μ nested directly in μ, and a
--   share holding a recursion referenced from inside a second one —
--   which is the shape whose nesting the rank guard cannot read off the
--   term it compares, and so the one a fit read off the term alone
--   would be expected to miss.  THE BOUNDARY: entry states only, with
--   `ψ` the schedule's own `slotRd` rather than a reading chosen for
--   them; nothing here reaches a state the drain itself produced.  And
--   all three take their depth from the TERM's own recursion — the one
--   that has a slot at all has a SHARED one.  THREE MORE ROWS CLOSE
--   THAT ARM, which is where this statement's two histories meet: the
--   same recursion over a SCRIPTED slot, the switching strategy over
--   it, and the recursion over a slot delivering NOTHING in its
--   subscribe frame — the refuting shape itself rather than a
--   neighbour, since a count read at the frame is nought there.  The
--   guard is then comparing a term whose nesting is fixed outside its
--   own syntax against exactly that count, and the fit holds at all
--   three.  TWO MORE ENTER THE LAST FLAVOUR, a HOT slot, at the same
--   recursion and at a defer over it, so all three flavours are now
--   reached under a μ.  THE SECOND BOUNDARY is what that arm cannot
--   say: a hot slot is anchored at tick ZERO rather than at the
--   subscription, and every row here is an entry, so the two anchors
--   coincide at every one of them and nothing separates them.
-- PROBED: `Probed.Gate-Constant` — the GATE at its own door, which is
--   the shape this statement was false at: a defer registers a chain
--   the reading gave nothing, so the crossing read one against zero.
--   The rows pin BOTH sides separately at one, two and three nested
--   gates and both read ONE at every depth, so the fit lands on the
--   nose — a reading that leaves the gate free fails the term column
--   and one that walks the body fails the carried column, which is
--   what makes the region instantiated rather than argued.  That the
--   figure does not climb with nesting is the finding underneath: a
--   door subscribes the OUTER gate only and the body becomes a fresh
--   source's pending payload, subscribed later at its own door, so the
--   debt a door returns is one chain of one hop whatever sits beneath
--   it.  And the assembly's own conclusion is read back at each depth
--   off a real run at eight times the fuel the door needs, since
--   `hasDry` is what the fit is ultimately for and it was observed
--   wrong at this very shape.  THE BOUNDARY: gates over a literal and
--   no recursion — a gate under a μ is where the reading's invariance
--   is load-bearing rather than merely preserved, and that axis is the
--   fold rows of the first receipt above; a gate whose body is itself
--   scheduled late is reached by nothing here.
postulate
  entry-hop-fits : ∀ {n} {Γ : Ctx n} {t} (e : Closed Γ t)
    (ins : Slots Γ) →
    let ent = subscribeE (rootWitness e ins) e root 0 0 (sched-init e ins)
                (st-init e)
    in hopFits (proj₁ (proj₂ ent)) (proj₂ (proj₂ ent))

-- NOTHING BELOW THIS LINE IS THE MACHINE'S TO CHOOSE, AND THAT IS WHAT
-- THE ITERATED FOLD CLAUSE BOUGHT.  The fit at the door takes the
-- program and the telescope and no third quantity, and both drain
-- halves read their environment off the schedule, so the reading every
-- peel is stated against is a function of the program alone.  A
-- conclusion about `evaluate` is then a claim about what was written
-- rather than about a number the door happened to mint.
--
-- DEAD ROUTE: a reading whose fold clause is parameterised by a REFOLD
--   BOUND the machine seeds, which is what this statement compared
--   against while that clause exponentiated.  All `evaluate` has to
--   hand such a clause is a count of ARRIVALS, and a refold happens per
--   DELIVERY — so a cascade delivering entirely inside one subscribe
--   frame refolds once per literal of its source while consuming no
--   allowance at all, and the run emits `dried` at a source long
--   enough.  Neither repair available from outside the clause works: a
--   larger allowance moves the crossing rather than removing it, since
--   the source that crosses is lengthened for free, and no other
--   quantity the door can see counts deliveries either.  The count has
--   to come from the SOURCE's own reading, which is what an iterating
--   clause takes it from.

-- THE ASSEMBLY, AND THE ONLY THING IT ADDS IS THE SEEDING.  `evaluate`
-- concatenates its root burst with its drain, so dryness of the run is
-- dryness of neither half; the burst's is the subscription walk at the
-- root, entered at `rootTri`, and `rootTri-reads` is what says that
-- triple reads the program it is about to subscribe.  That reflexivity is
-- the one place the entry seeding has to be shown adequate, and it is
-- here rather than in the walk because the walk never sees it.
rank-sufficient :
  ∀ {n} {Γ : Ctx n} {t} (fuel : Fuel) (e : Closed Γ t) (ins : Slots Γ) →
  hasDry (evaluate fuel e ins) ≡ false
rank-sufficient {Γ = Γ} {t = t} fuel e ins =
  hasDry-++ (proj₁ ent) (drain fuel 1 (proj₁ (proj₂ ent)) (proj₂ (proj₂ ent)))
    (proj₁ (subscribe-dry-free (rootWitness e ins) e root 0 0
      (sched-init e ins) (st-init e) (rootTri-reads e ins) z≤n))
    (drain-dry-free fuel 1 (proj₁ (proj₂ ent)) (proj₂ (proj₂ ent))
      (entry-hop-fits e ins))
  where
  ent : Stream Γ t × Sched Γ × EvalSt e
  ent = subscribeE (rootWitness e ins) e root 0 0 (sched-init e ins)
          (st-init e)
