-- THE PROOF that the evaluator's output satisfies the protocol
-- automaton: evaluate-well-formed, the primitives' half of the
-- batching sandwich (see Verify-Batch-Simultaneous.The-Proof).
--
-- Architecture: a simulation, in three layers.
--   1. Inv (CONCRETE below) relates evaluator state to automaton
--      state between cascades.
--   2. Two frame relations — BurstInv (mid-subscribe-frame) and Mid
--      (mid-cascade, indexed by the chains still to fold) — both
--      CONCRETE records now, with entry/step/exit lemmas.  Proven:
--      burst-init, burst-final.  Postulated (all believed true and
--      properly hypothesised — no known-false placeholders): the
--      step lemmas
--      (subscribeE-wf, mid-step — the per-clause preservation
--      grind), mid-init, mid-skip, mid-final.  Budget sufficiency
--      is no longer assumed here: it is imported, proven, from
--      Verify-Budget-Sufficient.
--   3. The compositions — the subscribe frame, the chain fold, the
--      fuel loop, and the theorem — are all DEFINED, glued by
--      runProtocol's distribution over ++.
module Verify-Well-Formed where

-- SPLIT 2026-08-11 into 13 parts.  This file was 5,816 lines forming ONE mutual
-- block of 276 members with ZERO cycles -- an artefact of declaration order,
-- not recursion.  Nothing could make a check of it incremental and
-- `make agda-dev` had no cycle to break, so it was the one module in the repo
-- that could not be iterated on.
--
-- The cut is mechanical: parts are consecutive runs of the ORIGINAL text, at
-- boundaries where no definition depends on a later one.  Two definitions moved
-- to make every boundary safe -- `subscribe-wf` and `subscribeE-wf`'s signature,
-- both DOWN to sit after what they use.  No statement, proof or signature
-- changed.  Consumers are unaffected: the parts are re-exported here under the
-- original module name.
open import Verify-Well-Formed.Part13 public
